name: flutter_bot
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.15.0 <3.0.0"

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.1
dependencies:
  dotenv: ^4.0.1
  http: ^0.13.5
  intl: ^0.17.0
  nyxx: ^4.3.0
  nyxx_interactions: ^4.4.0
  riverpod: ^2.1.1
